
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


# Selecci\u00f3n de persistencia: BD o FICHERO
dao.implementation=BD

# Par\u00e1metros de conexi\u00f3n a la Base de Datos WorkApp
db.url=jdbc:mysql://localhost:3306/WorkApp?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
db.user=root
db.password=abcd*1234